controller:
  useIngressClassOnly: true
  service:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: "bedrock.prod.fr.moz.works"
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
      service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "Environment=prod,Service=bedrock,Region=fr,Name=bedrock-prod"
  scope:
    enabled: true
